### ISSUE TITLE
[Question]: Is it possible to run it on the browser?

### ISSUE THREAD

**Issue by alamenai** [jguddas/markdown-pdf#1]
Hi @jguddas ,

I read your code and would ask you if it's possible to create a React Hook ( works only browser ) using your code.

Thank you.

**Comment by jguddas** [comment]
The `md-to-html` code should work in the browser.

The `md-to-pdf` code is pretty bodged, it's just a wrapper around price, and not a very good one at that.

If I were to go about trying to generate PDFs in the browser, I would use the normal print dialog, it kinda already works, just needs some adjustments for the margins.
